### PR TITLE
Project features

### PR DESCRIPTION
**Pull request by uimarshall**
@TSE, Please TSE should try to uninstall old versions of React and install the new versions. Because the reviews I am getting are quite strange and it's becoming very stressful for me.
In this PR, I build a React capstone project based on a catalog of statistics. The following was implemented:

- The project is a single page application built with React and Redux
- The data that was retrieved from the API is stored in the Redux store
- I filtered the data that was retrieved from the API using a Filter stateless component
- Every page, the main page, and pages for each item have a unique route within the SPA
- The project is deployed and accessible online
- Add testing

**Note:** @Tse, I was sick and my system wasn't functioning well, hence my inability to submit the project on deadline day.
Kindly bear with me.

**After Review**
Everything is working perfectly both locally and hosted version. I only double-check the [live link](https://pokemon-catalogue-stats.herokuapp.com/)  and updated the Readme to include installation of Redux Devtools, see below.

You can install [Redux Devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)  in your preferred browser, I suspect this should make you run the project locally if you encounter any issue.

**After second review**
Remove Redux devtools extension.
Fix a broken link to live demo.

**After Third review**
Fix bug for the project to be functional
@Inyama(TSE) can confirm that the project is working perfectly.

### CODE REVIEW

**Comment by uimarshall** [comment]
@TSE, I was sick and my system wasn't functioning well, hence my inability to submit the project on deadline day.
Kindly bear with me.

**Comment by arslanbisharat** [comment]
> @Tse, I was sick and my system wasn't functioning well, hence my inability to submit the project on deadline day.
> Kindly bear with me.

Please add this in the Pull Request Message

**Comment by uimarshall** [comment]
> > @Tse, I was sick and my system wasn't functioning well, hence my inability to submit the project on deadline day.
> > Kindly bear with me.
> 
> Please add this in the Pull Request Message

@arslanbisharat . the comment has been added as advised.

**Comment by uimarshall** [comment]
@arslanbisharat and @bello, You can install [Redux Devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) in your preferred browser, I suspect this should make you run the project locally.
Also, I do not know why you said the live link is not working whereas it's working perfectly.
[Live demo](https://pokemon-catalogue-stats.herokuapp.com/)

**Comment by arslanbisharat** [comment]
> @arslanbisharat and @bello, You can install [Redux Devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) in your preferred browser, I suspect this should make you run the project locally.
> Also, I do not know why you said the live link is not working whereas it's working perfectly.
> [Live demo](https://pokemon-catalogue-stats.herokuapp.com/)

You should have added these instructions in Readme. About the live link, I can see a blank screen.

**Comment by arslanbisharat** [comment]
Capture

**Comment by arslanbisharat** [comment]
> > @arslanbisharat and @bello, You can install [Redux Devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) in your preferred browser, I suspect this should make you run the project locally.
> > Also, I do not know why you said the live link is not working whereas it's working perfectly.
> > [Live demo](https://pokemon-catalogue-stats.herokuapp.com/)
> 
> You should have added these instructions in Readme. About the live link, I can see a blank screen.

If you need any help please reach out to me on slack.

**Comment by uimarshall** [comment]
@Inyama(TSE) can confirm that the project is working perfectly.

**Comment by uimarshall** [comment]
@TSE, Please TSE should try to uninstall old versions of React and install the new versions. Because the reviews I am getting are quite strange and it's becoming very stressful for me.

**Pull request merged**
